# compute_environment: LOCAL_MACHINE
# distributed_type: MULTI_GPU
# machine_rank: 0
# main_training_function: main
# mixed_precision: fp16
# num_machines: 1
# num_processes: 2
# rdzv_backend: static
# same_network: true
# tpu_env: []
# tpu_use_cluster: false
# tpu_use_sudo: false
# use_cpu: false

# compute_environment: LOCAL_MACHINE
# deepspeed_config:
#  deepspeed_config_file: ds_config.json
# distributed_type: DEEPSPEED
# fsdp_config: {}
# machine_rank: 0
# main_process_ip: null
# main_process_port: null
# main_training_function: main
# num_machines: 1
# num_processes: 2
# use_cpu: false

# compute_environment: LOCAL_MACHINE
# deepspeed_config:
#  gradient_accumulation_steps: 4
#  gradient_clipping: 1.0
#  offload_optimizer_device: none
#  offload_param_device: none
#  zero_stage: 2
# distributed_type: DEEPSPEED
# fsdp_config: {}
# machine_rank: 0
# gpu_ids: 0,1
# main_process_ip: null
# main_process_port: null
# mixed_precision: bf16
# num_machines: 1
# num_processes: 2
# use_cpu: false

compute_environment: LOCAL_MACHINE
distributed_type: 'NO'
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false